import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docSidebar: [
    'home',
    {
      type: 'category',
      label: 'Javascript tag',
      link: {
        "type": "generated-index",
        "description": "install and configure the SDK"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdk-js',
        },
        // {
        //   type: 'link',
        //   label: 'Changelog',
        //   href: 'https://screeb.notion.site/Javascript-tag-68e57473d23f4381933292cb299b285d',
        // }
      ],
    },
    {
      type: 'category',
      label: 'Android SDK',
      link: {
        "type": "generated-index",
        "description": "install and configure the SDK on Android devices"
      },
      items: [
        {
          type: 'autogenerated', dirName: 'sdk-android'
        },
        // {
        //   type: 'link',
        //   label: 'Changelog',
        //   href: 'https://screeb.notion.site/Android-SDK-4e588a60a5b94e40bfb44595c9defe60',
        // }
      ],
    },
    {
      type: 'category',
      label: 'iOS SDK',
      link: {
        "type": "generated-index",
        "description": "install and configure the SDK on IOS devices"
      },
      items: [
        {
          type: 'autogenerated', dirName: 'sdk-ios'
        },
        // {
        //   type: 'link',
        //   label: 'Changelog',
        //   href: 'https://screeb.notion.site/iOS-SDK-4ad6756875a14f2eb60711b86150a29d',
        // }
      ],
    },
    {
      type: 'category',
      label: 'React-Native SDK',
      items: [
        {
          type: 'autogenerated', dirName: 'sdk-react-native'
        },
        // {
        //   type: 'link',
        //   label: 'Changelog',
        //   href: 'https://screeb.notion.site/ReactNative-SDK-30e8dc27fa7a4dea979084d83e5140c3',
        // }
      ],
    },
    {
      type: 'category',
      label: 'Flutter SDK',
      link: {
        "type": "generated-index",
        "description": "install and configure the SDK on Flutter apps"
      },
      items: [
        {
          type: 'autogenerated', dirName: 'sdk-flutter'
        },
        // {
        //   type: 'link',
        //   label: 'Changelog',
        //   href: 'https://screeb.notion.site/Flutter-SDK-af72e1f601ac4785aa81bd13a61858c7',
        // }
      ],
    },
    {
      type: 'category',
      label: 'API and connectors',
      items: [
        {
          type: 'autogenerated', dirName: 'api-and-connectors'
        }
      ],
    }
  ],
  
};

export default sidebars;
