import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  /* docSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      label: "Changelog",
      href: "https://screeb.notion.site/Javascript-tag-68e57473d23f4381933292cb299b285d",
    },
  ], */

  docSidebar: [
    {
      type: "category",
      label: "Private",
      collapsible: false,

      link: {
        type: "generated-index",
        description: "Private Documentation",
        slug: "/",
      },
      items: [
        {
          type: "category",
          collapsed: false,
          collapsible: false,
          label: "SDK JS",
          
          link: {
            type: "generated-index",
            description: "SDK JS",
            slug: "/sdk-js",
          },

          items: [
            {
              type: "autogenerated",
              dirName: "sdk-js",
            },
          ],
        },
        {
          type: "category",
          collapsed: false,
          collapsible: false,
          label: "API and Connectors",

          link: {
            type: "generated-index",
            description: "API and Connectors",
            slug: "/api-and-connectors",
          },

          items: [
            {
              type: "autogenerated",
              dirName: "api-and-connectors",
            },
          ],
        },
        // {
        //   type: "link",
        //   label: "Changelog",
        //   href: "https://screeb.notion.site/Javascript-tag-68e57473d23f4381933292cb299b285d",
        // },
      ],
    },
  ],
};

export default sidebars;
